CREATE GRAPH medical;
SET GRAPH_PATH = medical;
-- Make Vertex Labels
CREATE VLABEL first_level_departments DISABLE INDEX;
CREATE VLABEL second_level_departments DISABLE INDEX;
CREATE VLABEL inspection_means DISABLE INDEX;
CREATE VLABEL treatment_plan DISABLE INDEX;
CREATE VLABEL manufacturer DISABLE INDEX;
CREATE VLABEL disease DISABLE INDEX;
CREATE VLABEL symptoms DISABLE INDEX;
CREATE VLABEL drug DISABLE INDEX;
CREATE VLABEL food DISABLE INDEX;
CREATE VLABEL recipe DISABLE INDEX;

-- Make Edge Labels
CREATE ELABEL highly_rated_medicines DISABLE INDEX;
CREATE ELABEL suitable_to_eat DISABLE INDEX;
CREATE ELABEL belong_to DISABLE INDEX;
CREATE ELABEL common_used DISABLE INDEX;
CREATE ELABEL complication DISABLE INDEX;
CREATE ELABEL avoid_eating DISABLE INDEX;
CREATE ELABEL affiliation_department DISABLE INDEX;
CREATE ELABEL treatment DISABLE INDEX;
CREATE ELABEL produce_medicine DISABLE INDEX;
CREATE ELABEL with_symptoms DISABLE INDEX;
CREATE ELABEL recommended_recipes DISABLE INDEX;
CREATE ELABEL diagnostic_tests DISABLE INDEX;