cd /home/work/liuytest/LLaMA-Factory/src/llamafactory/chat/
ASCEND_RT_VISIBLE_DEVICES=2,3,5 python3 -u liuy_test_all_model.py /home/work/liuytest/LLaMA-Factory/examples/inference/gemma9B_train_normal_prompt.yaml  /home/work/liuytest/大论文/2微调/ldbc_normal_test_7_3.json gemma9B_train_normal_prompt.json 
ASCEND_RT_VISIBLE_DEVICES=2,3,5 python3 -u liuy_test_all_model.py /home/work/liuytest/LLaMA-Factory/examples/inference/gemma9B_train_schema_prompt.yaml  /home/work/liuytest/大论文/2微调/ldbc_with_schema_prompt_test_7_3.json gemma9B_train_schema_prompt.json 
ASCEND_RT_VISIBLE_DEVICES=2,3,5 python3 -u liuy_test_all_model.py /home/work/liuytest/LLaMA-Factory/examples/inference/gemma9B_train_vector_prompt.yaml  /home/work/liuytest/大论文/2微调/ldbc_with_vector_prompt_test_7_3.json gemma9B_train_vector_prompt.json 
ASCEND_RT_VISIBLE_DEVICES=2,3,5 python3 -u liuy_test_all_model.py /home/work/liuytest/LLaMA-Factory/examples/inference/gemma9B_train_my_prompt.yaml  /home/work/liuytest/大论文/2微调/ldbc_with_schema_vector_prompt_test_7_3.json gemma9B_train_schema_vector_prompt.json 
ASCEND_RT_VISIBLE_DEVICES=2,3,5 python3 -u liuy_test_all_model.py /home/work/liuytest/LLaMA-Factory/examples/inference/GLM49B_train_normal_prompt.yaml /home/work/liuytest/大论文/2微调/ldbc_normal_test_7_3.json GLM49B_train_normal_prompt.json 
ASCEND_RT_VISIBLE_DEVICES=2,3,5 python3 -u liuy_test_all_model.py /home/work/liuytest/LLaMA-Factory/examples/inference/GLM49B_train_schema_prompt.yaml /home/work/liuytest/大论文/2微调/ldbc_with_schema_prompt_test_7_3.json GLM49B_train_schema_prompt.json 
ASCEND_RT_VISIBLE_DEVICES=2,3,5 python3 -u liuy_test_all_model.py /home/work/liuytest/LLaMA-Factory/examples/inference/GLM49B_train_vector_prompt.yaml /home/work/liuytest/大论文/2微调/ldbc_with_vector_prompt_test_7_3.json GLM49B_train_vector_prompt.json 
ASCEND_RT_VISIBLE_DEVICES=2,3,5 python3 -u liuy_test_all_model.py /home/work/liuytest/LLaMA-Factory/examples/inference/GLM49B_train_my_prompt.yaml /home/work/liuytest/大论文/2微调/ldbc_with_schema_vector_prompt_test_7_3.json GLM49B_train_schema_vector_prompt.json 
ASCEND_RT_VISIBLE_DEVICES=2,3,5 python3 -u liuy_test_all_model.py /home/work/liuytest/LLaMA-Factory/examples/inference/LLama8B_train_normal_prompt.yaml /home/work/liuytest/大论文/2微调/ldbc_normal_test_7_3.json LLama8B_train_normal_prompt.json   
ASCEND_RT_VISIBLE_DEVICES=2,3,5 python3 -u liuy_test_all_model.py /home/work/liuytest/LLaMA-Factory/examples/inference/LLama8B_train_schema_prompt.yaml /home/work/liuytest/大论文/2微调/ldbc_with_schema_prompt_test_7_3.json LLama8B_train_schema_prompt.json  
ASCEND_RT_VISIBLE_DEVICES=2,3,5 python3 -u liuy_test_all_model.py /home/work/liuytest/LLaMA-Factory/examples/inference/LLama8B_train_vector_prompt.yaml  /home/work/liuytest/大论文/2微调/ldbc_with_vector_prompt_test_7_3.json LLama8B_train_vector_prompt.json 
ASCEND_RT_VISIBLE_DEVICES=2,3,5 python3 -u liuy_test_all_model.py /home/work/liuytest/LLaMA-Factory/examples/inference/LLama8B_train_my_prompt.yaml  /home/work/liuytest/大论文/2微调/ldbc_with_schema_vector_prompt_test_7_3.json LLama8B_train_schema_vector_prompt.json 
ASCEND_RT_VISIBLE_DEVICES=2,3,5 python3 -u liuy_test_all_model.py /home/work/liuytest/LLaMA-Factory/examples/inference/Qwen2.57B_train_normal_prompt.yaml /home/work/liuytest/大论文/2微调/ldbc_normal_test_7_3.json Qwen2.57B_train_normal_prompt.json  
ASCEND_RT_VISIBLE_DEVICES=2,3,5 python3 -u liuy_test_all_model.py /home/work/liuytest/LLaMA-Factory/examples/inference/Qwen2.57B_train_schema_prompt.yaml /home/work/liuytest/大论文/2微调/ldbc_with_schema_prompt_test_7_3.json Qwen2.57B_train_schema_prompt.json  
ASCEND_RT_VISIBLE_DEVICES=2,3,5 python3 -u liuy_test_all_model.py /home/work/liuytest/LLaMA-Factory/examples/inference/Qwen2.57B_train_vector_prompt.yaml /home/work/liuytest/大论文/2微调/ldbc_with_vector_prompt_test_7_3.json Qwen2.57B_train_vector_prompt.json  
ASCEND_RT_VISIBLE_DEVICES=2,3,5 python3 -u liuy_test_all_model.py /home/work/liuytest/LLaMA-Factory/examples/inference/Qwen2.57B_train_my_prompt.yaml  /home/work/liuytest/大论文/2微调/ldbc_with_schema_vector_prompt_test_7_3.json Qwen2.57B_train_schema_vector_prompt.json 


