cd /home/work/liuytest/LLaMA-Factory/src/llamafactory/chat/
ASCEND_RT_VISIBLE_DEVICES=4 python3 -u liuy_test_all_model.py /home/work/liuytest/LLaMA-Factory/examples/inference/scala_1_9_Qwen2.57B_train_my_prompt.yaml /home/work/liuytest/大论文/2微调/scala_with_schema_vector_prompt_test_1_9.json scala_1_9_Qwen2.57B_my_prompt.json 
ASCEND_RT_VISIBLE_DEVICES=4 python3 -u liuy_test_all_model.py /home/work/liuytest/LLaMA-Factory/examples/inference/scala_2_8_Qwen2.57B_train_my_prompt.yaml /home/work/liuytest/大论文/2微调/scala_with_schema_vector_prompt_test_2_8.json scala_2_8_Qwen2.57B_my_prompt.json 
ASCEND_RT_VISIBLE_DEVICES=4 python3 -u liuy_test_all_model.py /home/work/liuytest/LLaMA-Factory/examples/inference/scala_3_7_Qwen2.57B_train_my_prompt.yaml /home/work/liuytest/大论文/2微调/scala_with_schema_vector_prompt_test_3_7.json scala_3_7_Qwen2.57B_my_prompt.json 
ASCEND_RT_VISIBLE_DEVICES=4 python3 -u liuy_test_all_model.py /home/work/liuytest/LLaMA-Factory/examples/inference/scala_4_6_Qwen2.57B_train_my_prompt.yaml /home/work/liuytest/大论文/2微调/scala_with_schema_vector_prompt_test_4_6.json scala_4_6_Qwen2.57B_my_prompt.json 
ASCEND_RT_VISIBLE_DEVICES=4 python3 -u liuy_test_all_model.py /home/work/liuytest/LLaMA-Factory/examples/inference/scala_5_5_Qwen2.57B_train_my_prompt.yaml /home/work/liuytest/大论文/2微调/scala_with_schema_vector_prompt_test_5_5.json scala_5_5_Qwen2.57B_my_prompt.json 
ASCEND_RT_VISIBLE_DEVICES=4 python3 -u liuy_test_all_model.py /home/work/liuytest/LLaMA-Factory/examples/inference/scala_6_4_Qwen2.57B_train_my_prompt.yaml /home/work/liuytest/大论文/2微调/scala_with_schema_vector_prompt_test_6_4.json scala_6_4_Qwen2.57B_my_prompt.json 
ASCEND_RT_VISIBLE_DEVICES=4 python3 -u liuy_test_all_model.py /home/work/liuytest/LLaMA-Factory/examples/inference/scala_7_3_Qwen2.57B_train_my_prompt.yaml /home/work/liuytest/大论文/2微调/scala_with_schema_vector_prompt_test_7_3.json scala_7_3_Qwen2.57B_my_prompt.json 
ASCEND_RT_VISIBLE_DEVICES=4 python3 -u liuy_test_all_model.py /home/work/liuytest/LLaMA-Factory/examples/inference/scala_8_2_Qwen2.57B_train_my_prompt.yaml /home/work/liuytest/大论文/2微调/scala_with_schema_vector_prompt_test_8_2.json scala_8_2_Qwen2.57B_my_prompt.json 
ASCEND_RT_VISIBLE_DEVICES=4 python3 -u liuy_test_all_model.py /home/work/liuytest/LLaMA-Factory/examples/inference/scala_9_1_Qwen2.57B_train_my_prompt.yaml /home/work/liuytest/大论文/2微调/scala_with_schema_vector_prompt_test_9_1.json scala_9_1_Qwen2.57B_my_prompt.json 