cd /home/work/liuytest/LLaMA-Factory/src/llamafactory/chat/
ASCEND_RT_VISIBLE_DEVICES=1 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/gemma9B_train_normal_prompt.yaml  /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/medical_normal.json                       medical_gemma9B_train_normal_prompt.json
ASCEND_RT_VISIBLE_DEVICES=1 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/gemma9B_train_schema_prompt.yaml  /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/medical_with_schema_prompt.json           medical_gemma9B_train_schema_prompt.json
ASCEND_RT_VISIBLE_DEVICES=1 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/gemma9B_train_vector_prompt.yaml  /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/medical_with_vector_prompt.json           medical_gemma9B_train_vector_prompt.json
ASCEND_RT_VISIBLE_DEVICES=1 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/gemma9B_train_my_prompt.yaml      /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/medical_with_schema_vector_prompt.json    medical_emma9B_train_schema_vector_prompt.json
ASCEND_RT_VISIBLE_DEVICES=1 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/GLM49B_train_normal_prompt.yaml /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/medical_normal.json                         medical_GLM49B_train_normal_prompt.json
ASCEND_RT_VISIBLE_DEVICES=1 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/GLM49B_train_schema_prompt.yaml /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/medical_with_schema_prompt.json             medical_GLM49B_train_schema_prompt.json
ASCEND_RT_VISIBLE_DEVICES=1 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/GLM49B_train_vector_prompt.yaml /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/medical_with_vector_prompt.json             medical_GLM49B_train_vector_prompt.json
ASCEND_RT_VISIBLE_DEVICES=1 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/GLM49B_train_my_prompt.yaml     /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/medical_with_schema_vector_prompt.json      medical_GLM49B_train_schema_vector_prompt.json
ASCEND_RT_VISIBLE_DEVICES=1 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/LLama8B_train_normal_prompt.yaml  /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/medical_normal.json                       medical_LLama8B_train_normal_prompt.json  
ASCEND_RT_VISIBLE_DEVICES=1 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/LLama8B_train_schema_prompt.yaml  /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/medical_with_schema_prompt.json           medical_LLama8B_train_schema_prompt.json 
ASCEND_RT_VISIBLE_DEVICES=1 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/LLama8B_train_vector_prompt.yaml  /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/medical_with_vector_prompt.json           medical_LLama8B_train_vector_prompt.json
ASCEND_RT_VISIBLE_DEVICES=1 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/LLama8B_train_my_prompt.yaml      /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/medical_with_schema_vector_prompt.json    medical_LLama8B_train_schema_vector_prompt.json
ASCEND_RT_VISIBLE_DEVICES=1 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/Qwen2.57B_train_normal_prompt.yaml /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/medical_normal.json                      medical_Qwen2.57B_train_normal_prompt.json 
ASCEND_RT_VISIBLE_DEVICES=1 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/Qwen2.57B_train_schema_prompt.yaml /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/medical_with_schema_prompt.json          medical_Qwen2.57B_train_schema_prompt.json 
ASCEND_RT_VISIBLE_DEVICES=1 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/Qwen2.57B_train_vector_prompt.yaml /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/medical_with_vector_prompt.json          medical_Qwen2.57B_train_vector_prompt.json 
ASCEND_RT_VISIBLE_DEVICES=1 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/Qwen2.57B_train_my_prompt.yaml     /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/medical_with_schema_vector_prompt.json   medical_Qwen2.57B_train_schema_vector_prompt.json