cd /home/work/liuytest/LLaMA-Factory/src/llamafactory/chat/
ASCEND_RT_VISIBLE_DEVICES=0 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/gemma9B_train_normal_prompt.yaml  /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/finbench_normal.json                       finbench_gemma9B_train_normal_prompt.json
ASCEND_RT_VISIBLE_DEVICES=0 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/gemma9B_train_schema_prompt.yaml  /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/finbench_with_schema_prompt.json           finbench_gemma9B_train_schema_prompt.json
ASCEND_RT_VISIBLE_DEVICES=0 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/gemma9B_train_vector_prompt.yaml  /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/finbench_with_vector_prompt.json           finbench_gemma9B_train_vector_prompt.json
ASCEND_RT_VISIBLE_DEVICES=0 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/gemma9B_train_my_prompt.yaml      /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/finbench_with_schema_vector_prompt.json    finbench_emma9B_train_schema_vector_prompt.json
ASCEND_RT_VISIBLE_DEVICES=0 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/GLM49B_train_normal_prompt.yaml /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/finbench_normal.json                        finbench_GLM49B_train_normal_prompt.json
ASCEND_RT_VISIBLE_DEVICES=0 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/GLM49B_train_schema_prompt.yaml /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/finbench_with_schema_prompt.json            finbench_GLM49B_train_schema_prompt.json
ASCEND_RT_VISIBLE_DEVICES=0 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/GLM49B_train_vector_prompt.yaml /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/finbench_with_vector_prompt.json            finbench_GLM49B_train_vector_prompt.json
ASCEND_RT_VISIBLE_DEVICES=0 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/GLM49B_train_my_prompt.yaml     /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/finbench_with_schema_vector_prompt.json     finbench_GLM49B_train_schema_vector_prompt.json
ASCEND_RT_VISIBLE_DEVICES=0 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/LLama8B_train_normal_prompt.yaml  /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/finbench_normal.json                      finbench_LLama8B_train_normal_prompt.json  
ASCEND_RT_VISIBLE_DEVICES=0 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/LLama8B_train_schema_prompt.yaml  /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/finbench_with_schema_prompt.json          finbench_LLama8B_train_schema_prompt.json 
ASCEND_RT_VISIBLE_DEVICES=0 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/LLama8B_train_vector_prompt.yaml  /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/finbench_with_vector_prompt.json          finbench_LLama8B_train_vector_prompt.json
ASCEND_RT_VISIBLE_DEVICES=0 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/LLama8B_train_my_prompt.yaml      /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/finbench_with_schema_vector_prompt.json   finbench_LLama8B_train_schema_vector_prompt.json
ASCEND_RT_VISIBLE_DEVICES=0 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/Qwen2.57B_train_normal_prompt.yaml /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/finbench_normal.json                     finbench_Qwen2.57B_train_normal_prompt.json 
ASCEND_RT_VISIBLE_DEVICES=0 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/Qwen2.57B_train_schema_prompt.yaml /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/finbench_with_schema_prompt.json         finbench_Qwen2.57B_train_schema_prompt.json 
ASCEND_RT_VISIBLE_DEVICES=0 python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/Qwen2.57B_train_vector_prompt.yaml /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/finbench_with_vector_prompt.json         finbench_Qwen2.57B_train_vector_prompt.json 
ASCEND_RT_VISIBLE_DEVICES=5 nohup python3 -u liuy_test_all_model.py  /home/work/liuytest/LLaMA-Factory/examples/inference/Qwen2.57B_train_my_prompt.yaml     /home/work/liuytest/大论文/3推理/跨领域测试数据集生成/finbench_with_schema_vector_prompt.json  finbench_Qwen2.57B_train_schema_vector_prompt.json &