CREATE GRAPH finbench;
SET GRAPH_PATH = finbench;
-- Make Vertex Labels
CREATE VLABEL account DISABLE INDEX;
CREATE VLABEL company DISABLE INDEX;
CREATE VLABEL loan DISABLE INDEX;
CREATE VLABEL medium DISABLE INDEX;
CREATE VLABEL person DISABLE INDEX;


-- Make Edge Labels
CREATE ELABEL AccountRepayLoan DISABLE INDEX;
CREATE ELABEL AccountTransferAccount DISABLE INDEX;
CREATE ELABEL AccountWithdrawAccount DISABLE INDEX;
CREATE ELABEL CompanyApplyLoan DISABLE INDEX;
CREATE ELABEL CompanyGuaranteeCompany DISABLE INDEX;
CREATE ELABEL CompanyInvestCompany DISABLE INDEX;
CREATE ELABEL CompanyOwnAccount DISABLE INDEX;
CREATE ELABEL LoanDepositAccount DISABLE INDEX;
CREATE ELABEL MediumSignInAccount DISABLE INDEX;
CREATE ELABEL PersonApplyLoan DISABLE INDEX;
CREATE ELABEL PersonGuaranteePerson DISABLE INDEX;
CREATE ELABEL PersonInvestCompany DISABLE INDEX;
CREATE ELABEL PersonOwnAccount DISABLE INDEX;